spring:
  application:
    name: LexSnap
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/lexsnap
    username: c0nf1dxnt
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

libretranslate:
  url: http://localhost:5000/translate
  api-key: ""
